Merge Jess's folder into main repository
broadinstitute/2021_09_01_VarChAMP pull request #21
Opened 2024-06-05 20:33 UTC by jessica-ewald

All of my downstream analysis is contained within the '7.downstream_analysis_jess' directory.

2024-06-08 10:13 UTC, shntnu approved these changes

2024-06-08 10:20 UTC, shntnu requested changes
Many of the diffs are permission changes:  100644 → 100755, means that the file has been updated to add execute permissions. 

You probably meant to do it for the scripts but not for the Jupyter notebooks.

To revert the file permissions for all files that are not .py in your directory, recursively, you can use the following command:

```
find . -type f ! -name "*.py" -exec chmod 644 {} +
```

2024-06-11 18:42 UTC, jessica-ewald commented
Ok, done @shntnu !

2024-06-25 17:56 UTC, shntnu approved these changes

2024-06-25 17:56 UTC, merged